### PR TITLE
Added Minecraft Dungeons, Time Tracking and more

### PR DESCRIPTION
**Pull request by urwrstkn8mare**
Added Minecraft Dungeons and time tracking. I've also made some other restructuring/small changes along the way hopefully they don't cause much trouble. For a GIF and some more information look at the README.md in my fork. The build.py was mainly for my own use to make developing easier. Sorry I did it in the fog_release branch. I just found it easier to work in. 

PS. I'm also planning to add support for MultiMC by double clicking the play button similar to how double clicking is used the the humble galaxy integration. Using this [decorator](https://github.com/UncleGoogle/galaxy-integration-humblebundle/blob/master/src/utils/decorators.py)

### CODE REVIEW

**Comment by TouwaStar** [comment]
@urwrstkn8mare  Nice!  
I will try to do a review of the code and test it on my pc in the upcoming days.

**Comment by urwrstkn8mare** [comment]
@TouwaStar, sorry to add more to your plate, but I've added MultiMC support to the plugin as well.

**Comment by urwrstkn8mare** [comment]
Ok, that's it, sorry for repeatedly adding even more commits and making this pull request even larger. 

I've just tested it for Mac and made some fixes/adjustments for it. Psutils wasn't working on mac for some reason so I just removed it and got the instance of Popen returned from launching the game and polled it to get the game status (running or not).

I've also found one unfixable issue with game time tracking where GOG Galaxy replaces game time if there was game time previously from another device with the plugin (not manually added). Unless we can save time to a cloud or GOG changes the API so we can get the game time stored in their cloud, there's no fixing it as far as I know.

**Comment by TouwaStar** [comment]
@urwrstkn8mare  no problem, i will probably check a look over the weekend. 

In the meantime I'll write up an email to friends of galaxy  if they maybe would want to switch their source of minecraft plugin to your fork so you won't have to wait for my review next time. Is that ok with you?

**Comment by urwrstkn8mare** [comment]
@TouwaStar I'm in no hurry so I can wait for your review. It would probably be safer if you reviewed and tested it as there may be issues I've missed. But if you want to switch it to my fork that's ok as well. It's up to you, just let me know as I would have to make the change the version number.

**Comment by TouwaStar** [comment]
I don't think i will find the time to go through the code in depth any time soon so i glanced over the code and tested the installation. Looks good.

**Comment by urwrstkn8mare** [comment]
thnx, just so you know the readme says I haven't tested it for mac. but I ended up testing it and fixing some stuff so I think that can be removed. just forgot to remove it sry

**Comment by TouwaStar** [comment]
np, changed it, thanks!

**Pull request merged**
