### PR TITLE
 Minor change to authentication phase

### PR DESCRIPTION
**Pull request by urwrstkn8mare**
I've addressed the concerns of @FriendsOfGalaxy in https://github.com/FriendsOfGalaxy/galaxy-integration-minecraft/pull/8#discussion_r491052701. I've unfortunately only been able to do the easy option as I've had less time in the holidays then I initially imagined. I've tested the migration but I'm not sure if I've done it properly so some additional testing by @TouwaStar or @FriendsOfGalaxy would be appreciated. 

@TouwaStar I think it would be better to wait for @FriendsOfGalaxy to confirm this before accepting the PR, otherwise, I might have to open another PR.

### CODE REVIEW

**Comment by FriendsOfGalaxy** [comment]
LGTM tested 👍

**Comment by FriendsOfGalaxy** [comment]
@TouwaStar @urwrstkn8mare

**Comment by urwrstkn8mare** [comment]
@TouwaStar, no pressure but any idea when you'll be able to review this?

**Comment by TouwaStar** [comment]
@urwrstkn8mare  sorry, wasn't looking at github lately, 
Looks ok, merging

**Pull request merged**
